framework:
    default_locale: ru
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks: ['en', 'ru']
